{% set version = "0.1.8" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpubr
  version: {{ version|replace("-", "_") }}

source:
  fn: ggpubr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggpubr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggpubr/ggpubr_{{ version }}.tar.gz
  sha256: 213a7b7b25167b04af80f21dd49edbae5faa630163db20ad359393daec17545f

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-gridextra
    - r-magrittr
    - r-purrr
    - r-scales
    - r-tidyr
  run:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-gridextra
    - r-magrittr
    - r-purrr
    - r-scales
    - r-tidyr

test:
  commands:
    - $R -e "library('ggpubr')"  # [not win]
    - "\"%R%\" -e \"library('ggpubr')\""  # [win]

about:
  home: http://www.sthda.com/english/rpkgs/ggpubr
  license: GPL-2
  summary: '''ggplot2'' is an excellent and flexible package for elegant data visualization in
    R. However the default generated plots requires some formatting before we can send
    them for publication. Furthermore, to customize a ''ggplot'', the syntax is opaque
    and this raises the level of difficulty for researchers with no advanced R programming
    skills. ''ggpubr'' provides some easy-to-use functions for creating and customizing
    ''ggplot2''- based publication ready plots.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
