# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Aefz71HsXojC30Zd2ozfE8xpHSpfAcF7+040aDEruK3xTEtfh5Oj8LE61gme4Ji+lHjglHz2gieF4EaL4FOqI5AWeGPOZFjo6IzvYIIigAYG3SS6Zhiz8kYZ0/b1MGGSri8X4GpVeAFQ4jH+Ceyz4rUU2TkaOIAVU+8XQStQGO0XyYSU0NYiT6/nYPogxRvIWRxv1G2+0iIH/Idr+I8xi5QiLA1S+air8T1bOuZTVwwh2BsqJX4rpBhYG3DNerD2MepB7HlH7DbZxsrF4YZJBfof4ZYmGWQLobLsaHYPFZzTqnVjQioXJyanB6gh0109psHtCo8TUva4D3ecehDXp9KFAsF1fUiJkz0xQOId6fhr4oHV1+s6MIfNlL6VxGQucT3Ywa90FAQ3MQ4oZREXDcfmOrdM928NDseG4MrWbtqzqZ1iV6/bx10GtR7asTICdK72E1iHLrtPjctZxyxZ0CeOaCoWu2RbJc/HmYfyMK4e1QzGDIlo1nQEbdo5w1IOoFljeSZWY4jz22suNXZQv/9gC4v2uT90Gd7+wosgM+ktyWSrcJ/up7tKty38Xkhq4JjzLkrMyWON8hhYDB+ywLUEwjRw0Qnx3EFCUe51VTxoRk+ZbxCU5XI98wOODqqvU2c2lCzbBgSNh6mxf4RSgxcBYaDuTUfsCIsm0LeB0B4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
