appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Aefz71HsXojC30Zd2ozfE8xpHSpfAcF7+040aDEruK3xTEtfh5Oj8LE61gme4Ji+lHjglHz2gieF4EaL4FOqI5AWeGPOZFjo6IzvYIIigAYG3SS6Zhiz8kYZ0/b1MGGSri8X4GpVeAFQ4jH+Ceyz4rUU2TkaOIAVU+8XQStQGO0XyYSU0NYiT6/nYPogxRvIWRxv1G2+0iIH/Idr+I8xi5QiLA1S+air8T1bOuZTVwwh2BsqJX4rpBhYG3DNerD2MepB7HlH7DbZxsrF4YZJBfof4ZYmGWQLobLsaHYPFZzTqnVjQioXJyanB6gh0109psHtCo8TUva4D3ecehDXp9KFAsF1fUiJkz0xQOId6fhr4oHV1+s6MIfNlL6VxGQucT3Ywa90FAQ3MQ4oZREXDcfmOrdM928NDseG4MrWbtqzqZ1iV6/bx10GtR7asTICdK72E1iHLrtPjctZxyxZ0CeOaCoWu2RbJc/HmYfyMK4e1QzGDIlo1nQEbdo5w1IOoFljeSZWY4jz22suNXZQv/9gC4v2uT90Gd7+wosgM+ktyWSrcJ/up7tKty38Xkhq4JjzLkrMyWON8hhYDB+ywLUEwjRw0Qnx3EFCUe51VTxoRk+ZbxCU5XI98wOODqqvU2c2lCzbBgSNh6mxf4RSgxcBYaDuTUfsCIsm0LeB0B4=}
