travis:
  secure:
    BINSTAR_TOKEN: T686C+0Qa8XfkGRl4BcIbUJQiF/uTfb3QJPdalL/VlO84G3ySfaKKMhDv2kPiLTRb/ten/Kw+n3Uh2tDKKNqJezM1j2ZN50ESrQNPVKjfGwubekwyW9HRY8rUf0dKIHyljFThFxuqPnHzrT4hEutbvD6UBvwXUSFhODiAMAmdUY8oWSFnP4ioeZTKivgHKoHfVzcYDBB2S/Y/hdwd/vqLKxKJnBGulKUrxaVb1++S0c69em5gJBsXruAQzNU2pcLMb1XiOSc7+XtX8IZ76hMG+WpdBGi3zNBovSGyC2GfVox8K7cO3G0mqbgg9D86xCzBilUcTynXqkQN9YW4+Q0qXfYgTCE+jF2zrr6jvQT2/1TVJpWHp8i+/O3Kclhr0UYZanm7WJAr+8WUXwzJDNBtTE/5OBWF+Ih3fp4Cr+tnOXF1H2YFf9JZKCbuSJhzE/h2NXBunTOxSgicF77iF3p4T8XcsrmFuJ+tmqcUZlxULZJOHgUjMZI7QDoO7+0GvZI4fV+LmkRO40vdc+6p4hurF66hfCzsmRFjtZUQLz752m3ckn+afQBM8yPSOGPs/Voxm9J88aI2WGZMPqpgyoq9pRKLc/VLSd8NadIofKmR/j7V3v+8TTozXac2iiwNnzi9tzFdUNr8XB7Z5iiHaEoKB/diNJfmialKK2eb4YS8Mo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
